
# This is a basic workflow to help you get started with Actions
name: UserActivity

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Checkout
          run: |
            pwd
            ls
        - name: install jmeter
          run: |
            java -version
            wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.zip
            unzip apache-jmeter-5.5.zip
            cd apache-jmeter-5.5/bin
            ./jmeter -v
            pwd
        - name: copy file
          uses: canastro/copy-file-action@master
          with:
              source: "./jmeter-plugins-random-csv-data-set-0.8.jar"
              target: "apache-jmeter-5.5/lib/ext"
        
        - name: install plugins
          run: |
            cd $GITHUB_WORKSPACE/apache-jmeter-5.5
            wget -q --no-check-certificate https://jmeter-plugins.org/files/packages/jpgc-dummy-0.4.zip  -P .
            unzip -o jpgc-dummy-0.4.zip  && rm jpgc-dummy-0.4.zip
            
        - name: run jmx scripts
          run: |
            cd $GITHUB_WORKSPACE/apache-jmeter-5.5/bin
            for i in $( ls $GITHUB_WORKSPACE/UserActivityGCP.jmx); do
            ./jmeter -n -t $i;
            done
        - name: Test Report
          uses: dorny/test-reporter@v1
          if: success() || failure()    # run this step even if previous step failed
          with:
            name: JEST Tests            # Name of the check run which will be created
            path: reports/jest-*.xml    # Path to test results
            reporter: jest-junit   
            
        - name: Upload Results
          uses: actions/upload-artifact@v2
          with:
            name: jmeter-results
            path: /home/runner/work/SmartApp-Jmeter-Github/SmartApp-Jmeter-Github/result.jtl
