# This is a basic workflow to help you get started with Actions
name: UserActivity

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Checkout
          run: |
            pwd
            ls
        - name: install jmeter
          run: |
            java -version
            wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.zip
            unzip apache-jmeter-5.5.zip
            cd apache-jmeter-5.5/bin
            ./jmeter -v
            pwd
        - name: download cmd runner in lib
          run : |
            cd apache-jmeter-5.5/lib
            curl -O https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2.1/cmdrunner-2.2.1.jar
        - name: install plugins
          run: |
            cd ext/
            curl -O https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.6/jmeter-plugins-manager-1.6.jar
        
            cd ..
            java  -jar cmdrunner-2.2.1.jar --tool org.jmeterplugins.repository.PluginManagerCMD install-all
            
        - name: run jmx scripts
          run: |
            cd $GITHUB_WORKSPACE/apache-jmeter-5.5/bin
            for i in $( ls $GITHUB_WORKSPACE/*.jmx); do
            ./jmeter -n -t $i;
            done
